I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 283, in script
    Je suis "Soirée avec Bolb"
Exception: Sayer 'Je' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 283, in script
    Je suis "Soirée avec Bolb"
  File "C:\Users\Florine Dobigny\Documents\Logiciels\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Florine Dobigny\Documents\Logiciels\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Je' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Le Cirque de la Passion 1.0
Sat Jan 27 23:43:50 2024
